/** Layer J — judgment에 쓰이는 field·outlet·질문 문구 (승인용 manifest 입력). */

export type LayerJOutlet = "§03·1차" | "§03·2차" | "§01·integrated";

export type LayerJJudgmentFieldSpec = {
  caseCode: string;
  outlet: LayerJOutlet;
  fieldId: string;
  questionLabel: string;
  /** J2 `other` / DI 시 항목명 */
  otherItemLabel: string;
};

export const LAYER_J_LEGACY_SLUGS = new Set<string>([
  "none",
  "no_stated",
  "partial",
  "confirmed",
  "traffic",
  "administrative",
  "labor_tax",
  "explanation_unknown",
  "attendance",
  "payment",
  "supplement",
]);

export const LAYER_J_JUDGMENT_FIELD_SPECS: LayerJJudgmentFieldSpec[] = [
  {
    caseCode: "01",
    outlet: "§03·1차",
    fieldId: "case01_violationContent",
    questionLabel:
      "교통국이나 다른 사람에게 설명받은 내용으로, 무엇이 문제라고 하는지 어떻게 이해하셨나요?",
    otherItemLabel: "통지 내용",
  },
  {
    caseCode: "01",
    outlet: "§03·1차",
    fieldId: "case01_authorityDemand",
    questionLabel: "교통국에서는 이 안내를 받은 뒤 구체적으로 무엇을 하라고 안내했나요?",
    otherItemLabel: "기관 요구",
  },
  {
    caseCode: "01",
    outlet: "§03·1차",
    fieldId: "case01_customerResponded",
    questionLabel: "이 안내를 받은 뒤 교통국에 대응한 경험이 있나요?",
    otherItemLabel: "대응 여부",
  },
  {
    caseCode: "01",
    outlet: "§03·1차",
    fieldId: "case01_responseDetail",
    questionLabel: "교통국에 어떤 형태로 대응했나요?",
    otherItemLabel: "대응 내용",
  },
  {
    caseCode: "01",
    outlet: "§03·1차",
    fieldId: "case01_deadline",
    questionLabel: "교통국에서 대응해야 하는 기한에 대해 어떻게 안내받으셨나요?",
    otherItemLabel: "대응 기한",
  },
  {
    caseCode: "01",
    outlet: "§03·2차",
    fieldId: "case01_factRelationship",
    questionLabel:
      "교통국에서 설명받은 내용과, 제가 알고 있는 실제 상황을 비교하면 어떤가요?",
    otherItemLabel: "사실 관계",
  },
  {
    caseCode: "01",
    outlet: "§03·2차",
    fieldId: "case01_factConflictFacet",
    questionLabel:
      "교통국이 말한 내용과 실제로 다르다고 보는 점은 무엇에 가장 가깝나요?",
    otherItemLabel: "사실 차이",
  },
  {
    caseCode: "01",
    outlet: "§03·2차",
    fieldId: "case01_spatiotemporalFacet",
    questionLabel: "그 날짜·장소·상황을 지금 어떤 방식으로 확인할 수 있나요?",
    otherItemLabel: "시공간 확인",
  },
  {
    caseCode: "01",
    outlet: "§03·2차",
    fieldId: "case01_compareRecordGap",
    questionLabel:
      "통지·안내 내용과 비교·대조하려면, 지금 특히 없거나 부족한 것을 골라 주세요. (여러 개 선택 가능)",
    otherItemLabel: "비교 자료",
  },
  {
    caseCode: "01",
    outlet: "§03·2차",
    fieldId: "case01_evidence",
    questionLabel:
      "지금 이 교통·행정 안내와 관련해, 확인하거나 제출에 활용할 수 있는 자료를 골라 주세요. (여러 개 선택 가능)",
    otherItemLabel: "확보 자료",
  },
  {
    caseCode: "01",
    outlet: "§03·2차",
    fieldId: "case01_languageAccessFact",
    questionLabel: "안내를 이해하거나 확인할 때 언어·통역 때문에 막힌 부분이 있나요?",
    otherItemLabel: "언어·통역",
  },
  {
    caseCode: "01",
    outlet: "§03·2차",
    fieldId: "case01_unclearDemandFact",
    questionLabel: "기관 요구에서 가장 불명확한 부분은 무엇인가요?",
    otherItemLabel: "요구 불명",
  },
  {
    caseCode: "01",
    outlet: "§03·2차",
    fieldId: "case01_noticeDeliveryFact",
    questionLabel: "교통국 안내를 처음 어떤 방식으로 받았나요?",
    otherItemLabel: "안내 수신",
  },
  {
    caseCode: "01",
    outlet: "§03·2차",
    fieldId: "case01_procedureStageFact",
    questionLabel: "이 안내가 처음 통지에 가깝나요, 추가·재통지에 가깝나요?",
    otherItemLabel: "통지 단계",
  },
  {
    caseCode: "01",
    outlet: "§03·2차",
    fieldId: "case01_officeIdentityFact",
    questionLabel: "안내를 준 기관·부서·담당을 어떻게 확인하고 있나요?",
    otherItemLabel: "기관 확인",
  },
  {
    caseCode: "01",
    outlet: "§03·2차",
    fieldId: "case01_correctTargetFact",
    questionLabel: "수정·확인하라고 한 대상은 무엇에 가깝나요?",
    otherItemLabel: "수정 대상",
  },
  {
    caseCode: "01",
    outlet: "§03·2차",
    fieldId: "case01_attendInstructionFact",
    questionLabel: "출석·소명 안내에서 가장 분명한 내용은 무엇인가요?",
    otherItemLabel: "출석 안내",
  },
  {
    caseCode: "01",
    outlet: "§03·2차",
    fieldId: "case01_supplementInstructionFact",
    questionLabel: "보완·재제출 안내의 핵심은 무엇인가요?",
    otherItemLabel: "보완 안내",
  },
  {
    caseCode: "01",
    outlet: "§03·2차",
    fieldId: "case01_paymentInstructionFact",
    questionLabel: "납부 안내의 성격은 무엇에 가깝나요?",
    otherItemLabel: "납부 안내",
  },
  {
    caseCode: "01",
    outlet: "§03·2차",
    fieldId: "case01_authorityFollowUpKind",
    questionLabel: "대응 후 교통국에서 어떤 회신·재요구를 받았나요?",
    otherItemLabel: "기관 회신",
  },
  {
    caseCode: "01",
    outlet: "§01·integrated",
    fieldId: "case01_customerResponded",
    questionLabel: "이 안내를 받은 뒤 교통국에 대응한 경험이 있나요?",
    otherItemLabel: "대응 여부",
  },
  {
    caseCode: "02",
    outlet: "§01·integrated",
    fieldId: "case02_paymentStatus",
    questionLabel: "지금까지 이 납부 요구에 대해 실제로 어떻게 하셨나요?",
    otherItemLabel: "납부 상태",
  },
  {
    caseCode: "03",
    outlet: "§01·integrated",
    fieldId: "case03_customerResponse",
    questionLabel: "출석·소명 요구에 대해 지금까지 어떻게 하셨나요?",
    otherItemLabel: "대응 상태",
  },
  {
    caseCode: "04",
    outlet: "§01·integrated",
    fieldId: "case04_customerResponse",
    questionLabel: "보완 요구에 대해 지금까지 어떻게 하셨나요?",
    otherItemLabel: "대응 상태",
  },
  {
    caseCode: "05",
    outlet: "§01·integrated",
    fieldId: "case05_customerResponse",
    questionLabel: "처분·통지에 대해 지금까지 어떻게 하셨나요?",
    otherItemLabel: "대응 상태",
  },
  {
    caseCode: "02",
    outlet: "§03·1차",
    fieldId: "case02_paymentSubject",
    questionLabel: "어떤 내용에 대한 납부 안내를 받으셨나요?",
    otherItemLabel: "납부 안내",
  },
  {
    caseCode: "02",
    outlet: "§03·1차",
    fieldId: "case02_confirmGoal",
    questionLabel: "이번 검토에서 가장 먼저 확인하고 싶은 것은 무엇인가요?",
    otherItemLabel: "확인 목표",
  },
  {
    caseCode: "02",
    outlet: "§03·1차",
    fieldId: "case02_demandAuthority",
    questionLabel: "납부를 요구한 기관은 어디로 보이나요?",
    otherItemLabel: "요구 기관",
  },
  {
    caseCode: "02",
    outlet: "§03·1차",
    fieldId: "case02_paymentStatus",
    questionLabel: "지금까지 이 납부 요구에 대해 실제로 어떻게 하셨나요?",
    otherItemLabel: "납부 상태",
  },
  {
    caseCode: "02",
    outlet: "§03·1차",
    fieldId: "case02_deadline",
    questionLabel: "납부 기한에 대해 어떻게 안내받으셨나요?",
    otherItemLabel: "납부 기한",
  },
  {
    caseCode: "02",
    outlet: "§03·2차",
    fieldId: "case02_situationMatch",
    questionLabel: "그 납부 요구가 실제 본인 상황과 맞다고 생각하시나요?",
    otherItemLabel: "상황 일치",
  },
  {
    caseCode: "02",
    outlet: "§03·2차",
    fieldId: "case02_paymentAmount",
    questionLabel: "안내받은 금액은 얼마인가요?",
    otherItemLabel: "납부 금액",
  },
  {
    caseCode: "02",
    outlet: "§03·2차",
    fieldId: "case02_nonPaymentNotice",
    questionLabel: "기한 내 납부하지 않으면 어떻게 된다고 안내받으셨나요?",
    otherItemLabel: "미납 안내",
  },
  {
    caseCode: "03",
    outlet: "§03·1차",
    fieldId: "case03_authorityDemand",
    questionLabel: "교통국에서는 어떤 조치를 요구하거나 안내했나요?",
    otherItemLabel: "기관 요구",
  },
  {
    caseCode: "03",
    outlet: "§03·1차",
    fieldId: "case03_confirmGoal",
    questionLabel: "이번 검토에서 가장 먼저 확인하고 싶은 것은 무엇인가요?",
    otherItemLabel: "확인 목표",
  },
  {
    caseCode: "03",
    outlet: "§03·1차",
    fieldId: "case03_customerResponse",
    questionLabel: "지금까지 교통국 요구에 어떻게 대응하셨나요?",
    otherItemLabel: "대응 내용",
  },
  {
    caseCode: "03",
    outlet: "§03·1차",
    fieldId: "case03_deadline",
    questionLabel: "출석·소명 등 대응 기한은 어떻게 안내받으셨나요?",
    otherItemLabel: "대응 기한",
  },
  {
    caseCode: "03",
    outlet: "§03·2차",
    fieldId: "case03_factRelationship",
    questionLabel: "기관이 확인하려는 내용과 실제 상황은 어떻게 다른가요?",
    otherItemLabel: "사실 관계",
  },
  {
    caseCode: "03",
    outlet: "§03·2차",
    fieldId: "case03_explanationDetail",
    questionLabel: "설명·소명 이후 기관 반응은 어떠했나요?",
    otherItemLabel: "소명 후 반응",
  },
  {
    caseCode: "03",
    outlet: "§03·2차",
    fieldId: "case03_evidence",
    questionLabel:
      "지금 출석·소명 요구와 관련해, 확인하거나 제출에 활용할 수 있는 자료를 골라 주세요. (여러 개 선택 가능)",
    otherItemLabel: "확보 자료",
  },
  {
    caseCode: "04",
    outlet: "§03·1차",
    fieldId: "case04_supplementTarget",
    questionLabel: "기관이 무엇을 보완하라고 요구한 상황에 가깝나요?",
    otherItemLabel: "보완 대상",
  },
  {
    caseCode: "04",
    outlet: "§03·1차",
    fieldId: "case04_confirmGoal",
    questionLabel: "이번 검토에서 가장 먼저 확인하고 싶은 것은 무엇인가요?",
    otherItemLabel: "확인 목표",
  },
  {
    caseCode: "04",
    outlet: "§03·1차",
    fieldId: "case04_customerResponse",
    questionLabel: "지금까지 보완 요구에 어떻게 대응하셨나요?",
    otherItemLabel: "대응 내용",
  },
  {
    caseCode: "04",
    outlet: "§03·1차",
    fieldId: "case04_deadline",
    questionLabel: "보완 제출 기한은 어떻게 안내받으셨나요?",
    otherItemLabel: "보완 기한",
  },
  {
    caseCode: "04",
    outlet: "§03·2차",
    fieldId: "case04_submissionRelation",
    questionLabel: "보완 요구 내용과 실제 제출·준비 상황은 어떻게 다른가요?",
    otherItemLabel: "제출 관계",
  },
  {
    caseCode: "04",
    outlet: "§03·2차",
    fieldId: "case04_addDocDetail",
    questionLabel:
      "보완 안내에서 추가로 제출해야 하는 서류 종류를 골라 주세요. (여러 개 선택 가능)",
    otherItemLabel: "추가 서류",
  },
  {
    caseCode: "04",
    outlet: "§03·2차",
    fieldId: "case04_modifyDetail",
    questionLabel:
      "보완 안내에서 수정·고쳐 써야 하는 항목을 골라 주세요. (여러 개 선택 가능)",
    otherItemLabel: "수정 항목",
  },
  {
    caseCode: "04",
    outlet: "§03·2차",
    fieldId: "case04_evidenceDetail",
    questionLabel:
      "안내에서 더 요구하는 증빙·자료 종류를 골라 주세요. (여러 개 선택 가능)",
    otherItemLabel: "추가 증빙",
  },
  {
    caseCode: "04",
    outlet: "§03·2차",
    fieldId: "case04_unclearFocus",
    questionLabel: "보완 요구 안내에서 가장 막힌 점은 무엇에 가깝나요?",
    otherItemLabel: "막힌 점",
  },
  {
    caseCode: "04",
    outlet: "§03·2차",
    fieldId: "case04_repeatSupplement",
    questionLabel: "이번 보완 요구는 이전에 제출했던 보완 내용과 비교하면 어떤 상황인가요?",
    otherItemLabel: "반복 보완",
  },
  {
    caseCode: "04",
    outlet: "§03·2차",
    fieldId: "case04_evidence",
    questionLabel:
      "지금 보완 요구와 관련해, 확인하거나 제출에 활용할 수 있는 자료를 골라 주세요. (여러 개 선택 가능)",
    otherItemLabel: "확보 자료",
  },
  {
    caseCode: "05",
    outlet: "§03·1차",
    fieldId: "case05_dispositionType",
    questionLabel: "통지된 처분·조치는 어떤 유형에 가깝나요?",
    otherItemLabel: "처분 유형",
  },
  {
    caseCode: "05",
    outlet: "§03·1차",
    fieldId: "case05_confirmGoal",
    questionLabel: "이번 검토에서 가장 먼저 확인하고 싶은 것은 무엇인가요?",
    otherItemLabel: "확인 목표",
  },
  {
    caseCode: "05",
    outlet: "§03·1차",
    fieldId: "case05_customerResponse",
    questionLabel: "처분 통지 이후 어떻게 대응하셨나요?",
    otherItemLabel: "대응 내용",
  },
  {
    caseCode: "05",
    outlet: "§03·1차",
    fieldId: "case05_deadline",
    questionLabel: "처분과 관련해 대응 기한은 어떻게 안내받으셨나요?",
    otherItemLabel: "대응 기한",
  },
  {
    caseCode: "05",
    outlet: "§03·2차",
    fieldId: "case05_factRelationship",
    questionLabel: "처분 내용과 실제 상황은 어떻게 다른가요?",
    otherItemLabel: "사실 관계",
  },
  {
    caseCode: "05",
    outlet: "§03·2차",
    fieldId: "case05_authorityFollowUp",
    questionLabel: "처분 이후 기관의 추가 안내·반응은 어떠했나요?",
    otherItemLabel: "기관 후속",
  },
  {
    caseCode: "05",
    outlet: "§03·2차",
    fieldId: "case05_dispositionOutcome",
    questionLabel: "현재 처분 결과·유지 여부는 어떻게 이해하시나요?",
    otherItemLabel: "처분 결과",
  },
  {
    caseCode: "05",
    outlet: "§03·2차",
    fieldId: "case05_explanationDetail",
    questionLabel: "기관에 제출한 소명·의견은 어떤 방식이었나요?",
    otherItemLabel: "소명 경로",
  },
  {
    caseCode: "05",
    outlet: "§03·2차",
    fieldId: "case05_factDetail",
    questionLabel: "실제 상황과 처분 사유는 어떤 점에서 다른가요?",
    otherItemLabel: "사실 차이",
  },
  {
    caseCode: "05",
    outlet: "§03·2차",
    fieldId: "case05_appealDetail",
    questionLabel: "이의제기·재검토 요청은 어떤 상태인가요?",
    otherItemLabel: "이의·재검토",
  },
  {
    caseCode: "05",
    outlet: "§03·2차",
    fieldId: "case05_submittedDocsDetail",
    questionLabel: "이번에 기관에 제출한 서류 종류를 골라 주세요. (여러 개 선택 가능)",
    otherItemLabel: "제출 서류",
  },
  {
    caseCode: "05",
    outlet: "§03·2차",
    fieldId: "case05_evidence",
    questionLabel:
      "지금 처분·조치와 관련해, 확인하거나 제출에 활용할 수 있는 자료를 골라 주세요. (여러 개 선택 가능)",
    otherItemLabel: "확보 자료",
  },
  {
    caseCode: "06",
    outlet: "§03·1차",
    fieldId: "case06_documentNature",
    questionLabel: "받은 문서는 어떤 성격에 가깝나요?",
    otherItemLabel: "문서 성격",
  },
  {
    caseCode: "06",
    outlet: "§03·1차",
    fieldId: "case06_requiredActionCandidate",
    questionLabel: "문서에서 기관이 요구하는 조치는 무엇으로 보이나요?",
    otherItemLabel: "요구 조치",
  },
  {
    caseCode: "06",
    outlet: "§03·1차",
    fieldId: "case06_customerResponse",
    questionLabel: "이 문서를 받은 뒤 지금까지 어떻게 하셨나요?",
    otherItemLabel: "대응 내용",
  },
  {
    caseCode: "06",
    outlet: "§03·2차",
    fieldId: "case06_paymentNature",
    questionLabel: "무엇에 대한 비용이라고 안내받았나요?",
    otherItemLabel: "비용 성격",
  },
  {
    caseCode: "06",
    outlet: "§03·2차",
    fieldId: "case06_paymentAmountKnown",
    questionLabel: "얼마를 내라고 안내받았나요?",
    otherItemLabel: "납부 금액",
  },
  {
    caseCode: "06",
    outlet: "§03·2차",
    fieldId: "case06_paymentSituationMatch",
    questionLabel: "그 금액이 실제 본인 상황과 맞다고 생각하시나요?",
    otherItemLabel: "금액·상황 일치",
  },
  {
    caseCode: "06",
    outlet: "§03·2차",
    fieldId: "case06_paymentNonPaymentNotice",
    questionLabel: "미납 시 어떤 조치가 있다고 안내받으셨나요?",
    otherItemLabel: "미납 안내",
  },
  {
    caseCode: "06",
    outlet: "§03·2차",
    fieldId: "case06_attendanceFactMatch",
    questionLabel: "기관이 문제 삼는 내용이 실제 상황과 맞다고 생각하시나요?",
    otherItemLabel: "출석·사실 일치",
  },
  {
    caseCode: "06",
    outlet: "§03·2차",
    fieldId: "case06_submissionRelation",
    questionLabel: "보완·제출 요구와 실제 준비 상황은 어떻게 다른가요?",
    otherItemLabel: "제출 관계",
  },
  {
    caseCode: "06",
    outlet: "§03·2차",
    fieldId: "case06_dispositionFactMatch",
    questionLabel: "처분·조치 내용과 실제 상황은 어떻게 다른가요?",
    otherItemLabel: "처분·사실 관계",
  },
  {
    caseCode: "06",
    outlet: "§03·2차",
    fieldId: "case06_unclearFactRelation",
    questionLabel: "문서 내용과 실제 상황을 비교하면 어떤가요?",
    otherItemLabel: "내용·사실 관계",
  },
];
