#!/usr/bin/env bash
# Idempotent bootstrap for the VFBCAI platform Cloud Agent environment.
# Prepares two apps:
#   1. vfbc-platform          — Next.js 16 web app (npm)
#   2. services/legal-rag     — self-contained Python legal-search service
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

echo "==> [1/4] Installing Next.js app dependencies (npm ci)"
npm ci

echo "==> [2/4] Ensuring local env placeholders (.env.local)"
# The web app reads several backend secrets at module-load time (Supabase,
# Resend). Without them the app cannot even render its UI, so we write
# clearly-marked placeholders for any variable that is NOT already provided by
# the real environment (e.g. Cursor Secrets). Real env vars always win over
# .env.local at runtime, so adding real credentials as secrets just works.
ENV_FILE="$ROOT/.env.local"
add_placeholder() {
  local key="$1" value="$2"
  # Skip if the variable is already set in the real environment.
  if [ -n "${!key:-}" ]; then
    return
  fi
  # Skip if it is already present in .env.local.
  if [ -f "$ENV_FILE" ] && grep -q "^${key}=" "$ENV_FILE"; then
    return
  fi
  echo "${key}=${value}" >>"$ENV_FILE"
}

if [ ! -f "$ENV_FILE" ]; then
  cat >"$ENV_FILE" <<'EOF'
# Local development placeholders generated by .cursor/install.sh.
# Real environment variables (e.g. Cursor Secrets) take precedence over these,
# so add real Supabase / Resend / OpenAI credentials as secrets to enable live
# functionality.
EOF
fi

add_placeholder NEXT_PUBLIC_SUPABASE_URL "https://placeholder.supabase.co"
add_placeholder NEXT_PUBLIC_SUPABASE_ANON_KEY "placeholder-anon-key"
add_placeholder SUPABASE_SERVICE_ROLE_KEY "placeholder-service-role-key"
add_placeholder NEXT_PUBLIC_SITE_URL "http://localhost:3000"
add_placeholder RESEND_API_KEY "re_placeholder"
add_placeholder RESEND_FROM_EMAIL "VFBCAI <onboarding@resend.dev>"

echo "==> [3/4] Ensuring Python venv tooling (python3-venv)"
if ! python3 -c "import ensurepip" >/dev/null 2>&1; then
  sudo apt-get update -qq
  sudo apt-get install -y -qq python3-venv
fi

echo "==> [4/4] Installing services/legal-rag Python dependencies"
cd "$ROOT/services/legal-rag"
if [ ! -x ".venv/bin/python" ]; then
  python3 -m venv .venv
fi
./.venv/bin/python -m pip install --quiet --upgrade pip
./.venv/bin/pip install --quiet -r requirements.txt

echo "==> Install complete."
